import { ButtonLink } from 'components/Button/ButtonLink/ButtonLink';
import { HeroTitle } from 'components/HeroTitle/HeroTitle';
import { HomeCuratedImages } from 'components/Home/HomeSectionImagesRow';
import React from 'react';
import { Modules } from 'types/main';

export const AlejandroAndTaylorHomeSection = () => {
  return (
    <section>
      <HeroTitle accentColor={'text-original'} subtitle="ALEJANDRO & TAYLOR">
        Mirage Gallery started with creating entirely{' '}
        <span className="underline text-original">A.I. generated artists.</span>
      </HeroTitle>
      <p className="mx-auto text-lg text-gray-600 md:text-3xl ">
        Each part of the artists below - from their artwork to their headshot
        and biography - has been generated by artificial intelligence.
      </p>
      <div className="relative">
        <div className="absolute top-0 bottom-0 left-0 w-96 bg-gradient-to-r from-white via-white/30 to-transparent" />
        <div className="absolute top-0 bottom-0 right-0 w-96 bg-gradient-to-l from-white via-white/30 to-transparent" />
        <HomeCuratedImages module={Modules.ALEJANDRO_AND_TAYLOR} />
      </div>
      <div className="flex items-center justify-start mt-6">
        <ButtonLink
          className="flex items-center justify-center px-6 py-4 text-white bg-native"
          href="/alejandro-and-taylor"
          showRightArrow
          text="Explore Alejandro & Taylor"
        />
      </div>
    </section>
  );
};
