import { HeroTitle } from 'components/HeroTitle/HeroTitle';
import React from 'react';

export const AlejandroAndTaylorHomeSection = () => {
  return (
    <section>
      <HeroTitle accentColor={'text-original'} subtitle="ALEJANDRO & TAYLOR">
        Mirage Gallery started with creating entirely{' '}
        <span className="underline text-original">A.I. generated artists.</span>
      </HeroTitle>
      <p className="mx-auto text-lg text-gray-600 md:text-3xl ">
        Each part of the artists below - from their artwork to their headshot
        and biography - has been generated by artificial intelligence.
      </p>
    </section>
  );
};
